module.exports = {
  preset: "ts-jest",
  testEnvironment: "node",
  testMatch: ["<rootDir>/src/**/?(*.)+(spec|test).[jt]s?(x)"],
  verbose: false,
  silent: false,
  testLocationInResults: true,
  collectCoverage: false,
  coverageReporters: ["text"],
  setupFilesAfterEnv: ["<rootDir>/jest.setup.js"],
  collectCoverageFrom: [
    "src/**/*.{js,ts}",
    "!src/**/*.test.{js,ts}",
    "!src/**/*.spec.{js,ts}",
    "!src/generated/**/*",
    "!**/node_modules/**",
    "!**/dist/**",
    "!**/build/**",
  ],
};
