service: store-config
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  stage: dev
  region: us-east-1
  profile: store-config # your aws configuration profile name
  runtime: nodejs20.x
  memorySize: 512
  timeout: 15
  logRetentionInDays: 14
  versionFunctions: false
  architecture: arm64
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/store-config-table-${self:provider.stage}"
            - "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/store-config-table-${self:provider.stage}/index/*"

package:
  individually: true

functions:
  apply:
    handler: functions/apply.handler
    description: Apply changes to App Store Connect
    timeout: 20 # API Gateway has a 30 second timeout
    memorySize: 1024
    events:
      - http:
          path: apply
          method: post
          authorizer:
            name: auth
            identitySource: method.request.header.X-StoreConfig-ApiKey
            type: request
  auth:
    handler: functions/authorizer.handler
    description: Custom Lambda authorizer for API Gateway
    timeout: 10
    memorySize: 256
    environment:
      STORE_CONFIG_TABLE_NAME: store-config-table-${self:provider.stage}
  payment-webhook:
    handler: functions/payment-webhook.handler
    description: Paddle payment webhook handler
    timeout: 15
    memorySize: 512
    events:
      - http:
          path: payment-webhook
          method: post
          cors: true

resources:
  Resources:
    StoreConfigTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: store-config-table-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: gsiPk
            AttributeType: S
          - AttributeName: gsiSk
            AttributeType: S
          - AttributeName: gsi2Pk
            AttributeType: S
          - AttributeName: gsi2Sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: gsi-api-key
            KeySchema:
              - AttributeName: gsiPk
                KeyType: HASH
              - AttributeName: gsiSk
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: gsi2-customer
            KeySchema:
              - AttributeName: gsi2Pk
                KeyType: HASH
              - AttributeName: gsi2Sk
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        Tags:
          - Key: Environment
            Value: ${self:provider.stage}
          - Key: Service
            Value: ${self:service}
